### ISSUE TITLE
Build failures with Release v1.0.0

### ISSUE THREAD

**Issue by lmeinen** [nkast/Aether.Extras#2]
For the Release v1.0.0 netstandard2.0 artifacts Aether.Animation.dll, Aether.Content.pipeline.AnimationImporters.dll and Aether.Content.Pipeline.GraphicsImporters.dll we get the following build errors after including them as mgcb references:

> Failed to load assembly '.../lib/Aether.[_insert artifact name here_].dll': Unable to load one or more of the requested types.
>   Could not load file or assembly 'MonoGame.Framework, Version=3.8.9102.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> 
>   Could not load file or assembly 'MonoGame.Framework, Version=3.8.9102.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> 
>   Could not load file or assembly 'MonoGame.Framework, Version=3.8.9102.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> 
>   Could not load file or assembly 'MonoGame.Framework, Version=3.8.9102.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> 
>   Could not load file or assembly 'MonoGame.Framework, Version=3.8.9102.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
> 
>   Could not load file or assembly 'MonoGame.Framework, Version=3.8.9102.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

We're using `MonoGame.Framework.DesktopGL v3.8.1.303` with `.NET 6.0`. Not sure if it's relevant, but the issue could be reproduced both on Linux and Windows systems.

We're relatively new to the .NET ecosystem so please let us know if we're missing something obvious or if there's any information missing.

**Comment by damian-666** [comment]
just tossing some ideas as i see you are taking care of things , and overhaul is sometimes gotta me done. we you are 8 years behind on opengl..    thankx..   i hope they might help..  if i get some decent tooling and UI il wil inform you.. i m stil on wiodws only but with scripting and tabbed views.   now trying to use parts of rosyln pad... sitil and opengl window in there.. if i have to make a image copy its so blazing  fast i can afford it..  i tried to email your other email but maybe you dont check it or too focused..

**i'm curious also if netstandard 2.0** is  going to be removed from the physics engine?  when i went fully to net 6, 7, 8 it was painful since i had a wpf level editor. now i ported that to WPF netcore for netcore8,  can link to any netcore6+ dll ( not netstandard) and i got 30 percent boost in performance for nothing.  Aslo i removed al locks in my code and render while doing physics, using producer consumer.   and custom timer resolution on windows.   I havent even used simed yea but hte optimizer does a lot on its own.. the Jitter.

couple more thing .. s**eems like reverb could almost work..   thxk..** if i can try it again i will..  without the xact parsing i dont care about that at all, but using my own sound files, and my own reverb settings set during the game play .  I just load wav files directly  for short sounds from a dll..  then my own physic based IDE to set reverb based on room side, etc.  

suggestions: 
and if yo**u look at Stride they did  two things.. Vulcan, integration in IDEs, vis shared buffer**.. kekekeki think did that.
also they took **sharpDx out and put in Silk Bindings as last generated, saying that opens the door to using more dx features.**   obviously you don't have to support them they are just public and or marked ( use at own risk, this is Silk direct exposure) 

another thing, looking at Bepu he does maintain two sets of shaders,  not that we have chatbots, i dint know it thats such a bad idea.. they can convert code and do hybrid GPU , cpu solutions , amazingly creative and code is something new for me.   ye you have to insist and micromanage the chatbots..

 I updated the wpf level editor to monogame 3.8.1   i dont use shared folder just dlls,... because they are problematic.  i used Craftwork games monogame in wpf  control..  ( two needed PRs are  its unmerged but works) took me  6 weeks to get off netstandard 2.0 and net4.8 at least directly linked. Now i'm free and clear of that so i'm wondering if you have legacy reasons to not build for net 6, or 8.. or if its blazer or something?   some companies could simply not leave netstandard to mg 3.8.1 , not do that.  they would go under. 
 
 and now looking at Avalonia docking  scripting and hosting monogame for 2d (  your engine or mine branch)  and 3d graphics with bepu.v2     i send a couple emails saying i look at how stride got Vulcan in there..    but they have a different shader transpiler.   they use wpf with maybe still net 4.8..    i do have so many issues with Avalonia and do want blazer and im a bit stuck.  
 
 
 Stride is dong will and much like monogame but it too bloated.. i don't want an ecs .. and the ide they have is broken and windows only but htey are onboarding many helpers..  i rather stick with monogame , because the bots code for it very well its so old.   so worth a spy in..

**Comment by damian-666** [comment]
building physics to net 6 was zero effort for me and putting your viewing lib in a dll, znero effort. BTW.. it was the legacy code and avalonia can hurt you.. i needed to go to gurus or spend hours getting a new control in the docking systems(s).. it needs work.  its not lie wpf that's done.    but its potential is more.  and it can update faster than 60 hz on timers and UI.. then i need to lock.. physics, im updating.. or i haven tried lockless ..  theres a wpf like, a paid wpf to avalonia, and a React and code only no axaml   route.. but it can kill your time.   the gurus  is Wiesław Šoltés  and kekekek..   a half hor wrok from them is like me hackihg a week on a tabbed window.     ok just ssome general advice   


Build failures with Release v1.0.0    
@lmeinen      


in the folder witht heh sln.. have a folder named .config wiht a dtnet_tools.json  and fix tje version maybe.. that is in the mg3.8.0 to mg.3.8.1   steps:



{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-mgcb": {
      "version": **"3.8.1.303",**=3.8.9102.0,****  <<-- fix this  ??  @nkast ??
      "commands": [
        "mgcb"
      ]
    },
    "dotnet-mgcb-editor": {
      "version": "3.8.1.303",   **=3.8.9102.0,**
      "commands": [
        "mgcb-editor"
      ]
    },
    "dotnet-mgcb-editor-linux": {
      "version": "3.8.1.303",
      "commands": [
        "mgcb-editor-linux"
      ]
    },
    "dotnet-mgcb-editor-windows": {
      "version": "3.8.1.303",
      "commands": [
        "mgcb-editor-windows"
      ]
    },
    "dotnet-mgcb-editor-mac": {
      "version": "3.8.1.303",
      "commands": [
        "mgcb-editor-mac"
      ]
    }
  }
}

**Comment by nkast** [comment]
In v1.1 the library moved to [KNI](https://github.com/kniEngine/kni/releases/tag/v3.9.9001) and MonoGame will no longer be supported.

The libraries worked with prior versions of MG but I wasn't be able to follow recent changes. In v3.8.1 MonoGame dropped NetStandard so there is no target to build the libraries against as NetStandard. The new compiler seem to be very strict with references and the bait-and-switch trick we used in the past doesn't seem to work.
So, you can try one of two things, 1) use the net40 libs, this might work under the .NetCore compatibility mode.
2) build the libraries from source, targeting MonoGame and upgrading the Framework to .Net6.

**Comment by nkast** [comment]
one more thing, 
you shouldn't include the Aether.Animation.dll in the .mgcb
That dll is only for the runtime.

**Comment by damian-666** [comment]
would you be able to target KNI? or are there a lot of breaking changes?   

the exes build the shader and content and you link in just teh .mgcb..  file to the exe as a linked file and onky that that the content builder thing..  as a monogamecontentreference with the content Nuget builder only on exes.     mine shows the basic  idea.. easy maintenance  .. touch a shader, test on all the targets...  no repeat code not copy no scripts.. the system does copy sutff around and tried to minimize rebuilding .all see the two samples that are branched as 3.81. 

https://github.com/damian-666/MGShadersXPlatform

**Comment by nkast** [comment]
Since v1.1.0 the library migrated to KNI framework.

Anyone that need to target MonoGame will have to use v1.0.0. 
Or to build the library from source will the necessary changes.
